name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install InvokeBuild
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.API_KEY }}
        shell: pwsh
        run: |
          Invoke-Build
          Publish-Module -Path /build/SeededGuid -NuGetApiKey $env:NUGET_KEY -Verbose
